### PR TITLE
Update required bcc version to 0.4.0

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vltrace/42)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/42#-:-KyQeE-pgAeJqSoEVqTU:bnfp4nl)*

**Review by GBuella — APPROVED** [review]

**Comment by ldorau** [comment]
API of libbcc was changed again, the patch has be changed too...

**Comment by ldorau** [comment]
PR was updated

**Comment by ldorau** [comment]
Waiting for the issue to be resolved:
https://github.com/iovisor/bcc/issues/1440

**Comment by ldorau** [comment]
It is ready to be merged :-)

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/42#-:-Kz5Mp8nN3W8b0YToAp8:bnfp4nl)*

**Pull request merged**
