### PR TITLE
Integrate Coverity

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vltrace/26)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/26)*

**Comment by ldorau** [comment]
It should be merged after PR https://github.com/pmem/vltrace/pull/27 has been merged

**Comment by marcinslusarz** [comment]
#30 is also needed.

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/26#-:-KuzUK63xdpgaLmAugum:bnfp4nl)*

**Comment by ldorau** [comment]
Rebased

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/26)*

**Comment by ldorau** [comment]
It is better to merge it after PR #29.

**Review by marcinslusarz — APPROVED** [review]

**Pull request merged**
