### PR TITLE
Only one instance of vltrace can run at the time

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vltrace/8)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Why can we only run one instance of vltrace at a time? Isn't this done per process?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/8#-:-KoiIv8oKIDqhTTY_4CL:b-peci2d)*

**Comment by ldorau** [comment]
It is because only one eBPF function can be attached to the raw tracepoint 'sys_exit' at the time. The following error occurs  when the second instance of vltrace tries to attach the second eBPF function to this raw tracepoint:
```
Attaching probes...
ioctl(PERF_EVENT_IOC_SET_BPF): File exists
ERROR(load_fn_and_attach_common): failed to attach eBPF function 'tracepoint' to tracepoint__sys_exit 'sys_exit': File exists
ERROR(attach_tp_exit): cannot attach tracepoint__sys_exit to 'raw_syscalls:sys_exit'. Exiting.
ERROR(main): no probes were attached
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/8#-:-KokyL7BBRY_IdYlKvfR:b5ft1rj)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/8#-:-KonsdNpPaUrUrR4oRq3:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/8)*

**Pull request merged**
