### PR TITLE
Remove lock file at exit only if it was created

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vltrace/12)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/12#-:-KpP0NdM5GmapR-VwJz8:bnfp4nl)*

**Comment by marcinslusarz** [comment]
FTR, this algorithm is racy. You should use flock. With that you would not even have to unlink this file...

**Comment by GBuella** [comment]
I personally don't understand what is the point of the whole `if (fd == -1) {` part, with reading the pid and whatnot. What is it for?

**Comment by GBuella** [comment]
BTW, what would be the problem, if multiple instances of vltrace would run?

**Comment by ldorau** [comment]
> BTW, what would be the problem, if multiple instances of vltrace would run?
>
https://github.com/pmem/vltrace/pull/8#issuecomment-314392160

**Comment by GBuella** [comment]
I see now, I should have followed PRs here, and what about my other question?
Why not just quit (with a meaningful message) when open fails?

**Comment by sarahjelinek** [comment]
I agree with Marcin. flock() is the best solution for this. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/12#-:-KpX3eiApL9in9wTMnsS:b-fti6fx)*

**Comment by ldorau** [comment]
A new version of this patch was submitted as a PR https://github.com/pmem/vltrace/pull/15

**Pull request closed without merging**
