### PR TITLE
Add multi-threaded test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/vltrace/31)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/CMakeLists.txt, line 66 at r1](https://reviewable.io:443/reviews/pmem/vltrace/31#-KvD9emSqshcLpFT_oLn:-KvD9emSqshcLpFT_oLo:b-5mmiok) ([raw file](https://github.com/pmem/vltrace/blob/3cd98f6f14dec230e7aa76e388afb887f0d743d8/test/CMakeLists.txt#L66)):*
> ```CMake
> 		else ()
> 			set(FMT "")
> 			set(WAIT "do-not-wait")
> ```

I don't understand why we need to wait for syscalls in text mode only.  Can you add a comment about why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/31)*

**Comment by ldorau** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/CMakeLists.txt, line 66 at r1](https://reviewable.io:443/reviews/pmem/vltrace/31#-KvD9emSqshcLpFT_oLn:-KvSD_8IBAv1908tjOXf:bsegvaj) ([raw file](https://github.com/pmem/vltrace/blob/3cd98f6f14dec230e7aa76e388afb887f0d743d8/test/CMakeLists.txt#L66)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I don't understand why we need to wait for syscalls in text mode only.  Can you add a comment about why?
</blockquote></details>

I added the comment:
```
			# Turn on the delay (busy wait) between syscalls only in the text mode,
			# because the text mode is much slower and it needs more time
			# for packet processing before the next packet arrives.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/31)*

**Comment by sarahjelinek** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/31)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/31#-:-KvSHR9oz2o9KACHne0q:bnfp4nl)*

**Pull request merged**
